### ISSUE TITLE
juju not working

### ISSUE THREAD

**Issue by jaime-ez** [PyBossa/pybossa-jujucharm#8]
Hi guys, your project seems great, but I haven been able to run it yet. juju status throws this:

environment: local
machines:
  "0":
    agent-state: started
    agent-version: 1.24.7.1
    dns-name: localhost
    instance-id: localhost
    series: trusty
    state-server-member-status: has-vote
  "1":
    instance-id: pending
    series: trusty
  "2":
    instance-id: pending
    series: trusty
services:
  juju-gui:
    charm: cs:trusty/juju-gui-51
    exposed: false
    service-status:
      current: unknown
      message: Waiting for agent initialization to finish
      since: 15 Mar 2016 00:52:09Z
    units:
      juju-gui/0:
        workload-status:
          current: unknown
          message: Waiting for agent initialization to finish
          since: 15 Mar 2016 00:52:09Z
        agent-status:
          current: allocating
          since: 15 Mar 2016 00:52:09Z
        agent-state: pending
        machine: "1"
  pybossa:
    charm: local:trusty/pybossa-0
    exposed: false
    service-status:
      current: unknown
      message: Waiting for agent initialization to finish
      since: 15 Mar 2016 00:53:11Z
    units:
      pybossa/0:
        workload-status:
          current: unknown
          message: Waiting for agent initialization to finish
          since: 15 Mar 2016 00:53:11Z
        agent-status:
          current: allocating
          since: 15 Mar 2016 00:53:11Z
        agent-state: pending
        machine: "2"
vagrant@vagrant-ubuntu-trusty-32:/vagrant$ 

and it stays there indefinitely...any ideas?
Thanks

**Comment by teleyinex** [comment]
Hi,

In all the machines you can see the **message**: Waiting for agent initialization to finish. Basically, the system is deploying everything in different Virtual Machines within your system, so you've to wait until you cannot see that message. The VMs are installing their software, and that's why you cannot access it yet. Can you try again after a few minutes?

**Comment by jaime-ez** [comment]
Thanks for the reply, the first time I waited for over 50 minutes and nothing happened, but today it took 1129 seconds and everythings works like a charm.
Best,
Jaime

**Comment by teleyinex** [comment]
Wow! Then, obviously the first time something went wrong. Nice to hear that the second time was fine!
